import { 
  UserProfile, 
  Shipment, 
  WarehouseItem, 
  Invoice, 
  NotificationItem, 
  ChatMessage 
} from '../types';

export const ADMIN_USER: UserProfile = {
  id: 'usr-admin',
  first_name: 'Administrador',
  last_name: 'RerF',
  email: 'admin@rerf.gt',
  phone: '+502 2345 6789',
  address: 'Oficinas Centrales RerF Logistics, Zona 10, Ciudad de Guatemala',
  address_references: 'Torre Empresarial RerF, Nivel 4',
  bio: 'Administrador general del sistema de logística nacional RerF.',
  role: 'admin',
  avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
};

export const ERICK_USER: UserProfile = {
  id: 'usr-erick',
  first_name: 'Erick',
  last_name: 'Jimenez',
  email: 'esolorzano@gmail.com',
  phone: '+502 4433 2211',
  address: 'Ciudad de Guatemala',
  address_references: 'Oficina Central',
  bio: 'Usuario registrado en RerF Logistics.',
  role: 'cliente',
  avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
};

export const INITIAL_USER: UserProfile = {
  id: 'usr-001',
  first_name: 'Carlos',
  last_name: 'Gómez',
  email: 'carlos.gomez@rerf.gt',
  phone: '+502 5512 3456',
  address: '10ma Calle 4-22 Zona 14, Ciudad de Guatemala',
  address_references: 'Frente a Plaza Futeca, edificio gris',
  bio: 'Cliente frecuente de envíos nacionales y almacenaje en bodega.',
  role: 'cliente',
  avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
};

export const MOCK_USERS_DIRECTORY: UserProfile[] = [
  { ...ERICK_USER },
  {
    id: 'usr-002',
    first_name: 'María',
    last_name: 'Fernández',
    email: 'maria.f@correo.com',
    phone: '+52 55 9876 5432',
    address: 'Calle Juárez #12',
    address_references: 'Edificio B, Depto 301',
    bio: 'Vendedora de artesanías y artículos para el hogar.',
    role: 'cliente',
    is_favorite: true,
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'usr-003',
    first_name: 'Alejandro',
    last_name: 'Ruiz',
    email: 'alex.ruiz@correo.com',
    phone: '+52 55 4567 8901',
    address: 'Blvd. Central #900',
    address_references: 'Junto a la farmacia',
    bio: 'Distribuidor mayorista de electrónicos.',
    role: 'cliente',
    is_favorite: true,
    avatar_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'usr-004',
    first_name: 'Laura',
    last_name: 'Méndez',
    email: 'laura.m@correo.com',
    phone: '+52 55 8765 4321',
    address: 'Av. Hidalgo #78',
    bio: 'Emprendedora de moda sustentable.',
    role: 'cliente',
    is_favorite: false,
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'usr-005',
    first_name: 'Roberto',
    last_name: 'Paredes',
    email: 'roberto.p@correo.com',
    phone: '+52 55 3344 5566',
    address: 'Circuito Colonias #40',
    bio: 'Envíos regulares de repuestos industriales.',
    role: 'cliente',
    is_favorite: false,
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  },
];

export const MOCK_SHIPMENTS: Shipment[] = [
  {
    id: 'ship-101',
    tracking_number: 'RERF-98234-GT',
    sender_id: 'usr-001',
    recipient_name: 'María Fernández',
    recipient_phone: '+52 55 9876 5432',
    delivery_address: 'Calle Juárez #12, Int 301',
    address_references: 'Portón negro con timbre azul',
    scheduled_date: '2026-09-22',
    description: 'Caja con artículos de cerámica artesanal',
    status: 'en_camino',
    payment_method: 'contra_entrega',
    payment_status: 'pendiente',
    total_amount: 185.50,
    agent_name: 'Carlos Piloto 04',
    packages: [
      {
        id: 'pkg-1',
        category: 'Hogar / Artesanías',
        name: 'Vajilla Cerámica',
        quantity: 1,
        weight_kg: 3.5,
        material: 'fragil',
        dimensions: '30x30x25 cm',
        description: 'Empaque reforzado con burbuja protectora',
      }
    ],
    created_at: '2026-09-20 09:30',
  },
  {
    id: 'ship-102',
    tracking_number: 'RERF-77120-MX',
    sender_id: 'usr-001',
    recipient_name: 'Alejandro Ruiz',
    delivery_address: 'Blvd. Central #900',
    address_references: 'Local de repuestos',
    scheduled_date: '2026-09-23',
    description: 'Piezas mecánicas de repuesto',
    status: 'pendiente',
    payment_method: 'tarjeta',
    payment_status: 'pagado',
    total_amount: 95.00,
    packages: [
      {
        id: 'pkg-2',
        category: 'Ferretería / Maquinaria',
        name: 'Engranes de precisión',
        quantity: 2,
        weight_kg: 5.0,
        material: 'fuerte',
        description: 'Caja de madera sellada',
      }
    ],
    created_at: '2026-09-21 11:15',
  },
  {
    id: 'ship-103',
    tracking_number: 'RERF-55401-EX',
    sender_id: 'usr-001',
    recipient_name: 'Laura Méndez',
    delivery_address: 'Av. Hidalgo #78',
    scheduled_date: '2026-09-18',
    description: 'Prendas de vestir en bolsas ecológicas',
    status: 'entregado',
    payment_method: 'efectivo',
    payment_status: 'pagado',
    total_amount: 65.00,
    packages: [
      {
        id: 'pkg-3',
        category: 'Ropa / Textiles',
        name: 'Lote playeras orgánicas',
        quantity: 4,
        weight_kg: 1.8,
        material: 'fuerte',
        description: 'Bolsa biodegradable',
      }
    ],
    created_at: '2026-09-17 14:00',
  },
  {
    id: 'ship-104',
    tracking_number: 'RERF-33219-RJ',
    sender_id: 'usr-001',
    recipient_name: 'Roberto Paredes',
    delivery_address: 'Circuito Colonias #40',
    scheduled_date: '2026-09-19',
    description: 'Material químico no tóxico',
    status: 'rechazado',
    rejection_reason: 'El tipo de líquido no cumple con la normativa de transporte seguro para motos.',
    payment_method: 'efectivo',
    payment_status: 'pendiente',
    total_amount: 110.00,
    created_at: '2026-09-19 08:20',
  },
];

export const MOCK_WAREHOUSE_ITEMS: WarehouseItem[] = [
  {
    id: 'wh-01',
    user_id: 'usr-001',
    product_type: 'Cajas de Calzado deportivo',
    description: '15 pares de tenis talla 27 empacados',
    material: 'fuerte',
    pickup_method: 'recogida_piloto',
    status: 'almacenado',
    storage_code: 'BOD-A12-N4',
    created_at: '2026-09-15',
  },
  {
    id: 'wh-02',
    user_id: 'usr-001',
    product_type: 'Lámparas de mesa vintage',
    description: '3 lámparas con base de cristal soplado',
    material: 'fragil',
    pickup_method: 'entrega_personal',
    status: 'almacenado',
    storage_code: 'BOD-F03-N1',
    created_at: '2026-09-18',
  },
  {
    id: 'wh-03',
    user_id: 'usr-001',
    product_type: 'Accesorios para celular',
    description: '50 fundas de silicón y protectores',
    material: 'fuerte',
    pickup_method: 'entrega_personal',
    status: 'en_transito',
    storage_code: 'BOD-C09-N2',
    created_at: '2026-09-20',
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    invoice_number: 'FAC-2026-0891',
    shipment_id: 'ship-101',
    description: 'Servicio de envío exprés frágil y seguro',
    amount: 185.50,
    status: 'pendiente',
    payment_method: 'Contra entrega',
    issued_date: '2026-09-21',
    due_date: '2026-09-25',
  },
  {
    id: 'inv-002',
    invoice_number: 'FAC-2026-0840',
    shipment_id: 'ship-103',
    description: 'Envío estándar zona urbana',
    amount: 65.00,
    status: 'pagado',
    payment_method: 'Efectivo',
    issued_date: '2026-09-17',
  },
  {
    id: 'inv-003',
    invoice_number: 'FAC-2026-0811',
    description: 'Renta mensual de espacio en Bodega Personal',
    amount: 250.00,
    status: 'pagado',
    payment_method: 'Tarjeta de Crédito',
    issued_date: '2026-09-01',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Envío en camino',
    message: 'Tu paquete RERF-98234-GT ha salido del centro de distribución con el piloto asignado.',
    type: 'envio',
    date: 'Hace 25 min',
    is_read: false,
  },
  {
    id: 'notif-2',
    title: 'Almacenaje confirmado',
    message: 'Tus lámparas vintage fueron recibidas con éxito en la bodega (BOD-F03-N1).',
    type: 'info',
    date: 'Hace 2 horas',
    is_read: false,
  },
  {
    id: 'notif-3',
    title: 'Factura emitida',
    message: 'Se generó la factura FAC-2026-0891 por un total de $185.50.',
    type: 'pago',
    date: 'Ayer',
    is_read: true,
  },
  {
    id: 'notif-4',
    title: 'Actualización del servicio',
    message: 'Ahora puedes solicitar recogida de tus paquetes en bodega directamente por piloto.',
    type: 'sistema' as any,
    date: 'Hace 3 días',
    is_read: true,
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    sender_id: 'support-1',
    sender_name: 'Moderación RERF',
    message: '¡Hola Carlos! Bienvenido al soporte técnico de RERF APP. ¿En qué podemos orientarte hoy?',
    created_at: '10:14 AM',
    is_support: true,
  },
  {
    id: 'msg-2',
    sender_id: 'usr-001',
    sender_name: 'Carlos Gómez',
    message: 'Hola, quería consultar la hora estimada de llegada de mi paquete RERF-98234-GT.',
    created_at: '10:15 AM',
  },
  {
    id: 'msg-3',
    sender_id: 'support-1',
    sender_name: 'Moderación RERF',
    message: 'El piloto se encuentra a aproximadamente 15 minutos de la dirección registrada. Puedes seguir la ruta en tiempo real desde la sección GPS.',
    created_at: '10:17 AM',
    is_support: true,
  },
];

export const MOCK_AI_MESSAGES: ChatMessage[] = [
  {
    id: 'ai-1',
    sender_id: 'bot-rerf',
    sender_name: 'Asistente IA RerF',
    message: '¡Hola! Soy tu Asistente Logístico Inteligente de RerF Logistics Guatemala. 🇬🇹📦\n\nPuedo ayudarte a consultar el estado de tus guías en tiempo real, calcular tarifas y fletes en Quetzales, revisar coberturas departamentales o gestionar tu inventario en bodega. ¿En qué te puedo colaborar hoy?',
    created_at: '08:00 AM',
    is_bot: true,
  },
];

export const MOCK_SUPPORT_CONTACTS = [
  {
    id: 'sup-1',
    name: 'Moderador 1 (Envíos)',
    role: 'Soporte de Logística y Rutas',
    status: 'En línea',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'sup-2',
    name: 'Moderador 2 (Bodega)',
    role: 'Atención a Bodega y Almacenaje',
    status: 'En línea',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'sup-3',
    name: 'Moderador 3 (Facturación)',
    role: 'Consultas de Pago y Facturas',
    status: 'Ocupado',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
  },
];
